name: Build and Test

on:
  push:
    branches-ignore: [ master ]
    # paths-ignore:
    #  - '**.yml'
  pull_request:
    branches-ignore: [ master ]
  workflow_dispatch:

env:
  SOLUTION_DIRECTORY : src
  SOLUTION_PATH : src/FluentSetups.sln
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: check branch
      if: github.ref == 'refs/heads/master'  
      run: echo github.ref

    - name: checkout branch
      uses: actions/checkout@v3

    - name: upload artifacts
      #if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3.0.0
      with:
        name: nugetPackage
        path: src\Release\*.nupkg
        retention-days: 1

  publish:
    needs: build
    runs-on: windows-latest
    #if: github.ref == 'refs/heads/master'
    steps:
    - name: download nuget
      if: github.ref == 'refs/heads/master'
      uses: actions/download-artifact@v3.0.0
      with:
        name: nugetPackage
        path: downloads
        
    - name: show download
      run: dir downloads
  
