name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: branch ${{ github.ref }}
      if: github.ref == 'refs/heads/master'  
      run: echo ${{ github.ref }}

    - name: checkout branch
      uses: actions/checkout@v3
      
    - name: build
      run: | 
        mkdir Release
        cd Release
        echo SomeText > MyPackage.txt
        

    - name: dir Release
      run: dir Release

    - name: Activate caching
      id: cache
      uses: actions/cache@v3
      with:
        path: /Release
        key: ${{ github.run_number }}
        

  publish:
    needs: build
    runs-on: windows-latest
    steps:
    - name: Activate caching
      id: cache
      uses: actions/cache@v2
      with:
        path: Cache
        key: ${{ github.run_number }}
        
    - name: show cache
      run: dir Cache
  
