name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: branch ${{ github.ref }}
      if: github.ref == 'refs/heads/master'  
      run: echo ${{ github.ref }}

    - name: checkout branch
      uses: actions/checkout@v3

    - name: Unique Name Generator Action
        # You may pin to the exact commit or the version.
        # uses: TGPSKI/name-generator-node-action@5c1c97cdae4ef40d21eb05f1a46ead10ac61037b
      uses: TGPSKI/name-generator-node-action@v2
      with:
        # How many words in the name
        length: 50
        # Name output case style
        #style: # default is lowerCase
        
        
    #- id: get_version
    #  uses: battila7/get-version-action@v2.2.1

    #- run: echo ${{ steps.get_version.outputs.version }}
    #- run: echo ${{ steps.get_version.outputs.version-without-v }}
    #- run: echo ${{ steps.get_version.outputs.is-semver }}
      
    - name: build
      run: | 
        mkdir Release
        cd Release
        echo SomeText > MyPackage.txt

    - name: upload artifacts
      if: ${{github.ref == 'refs/heads/master'}}
      uses: actions/upload-artifact@v3.0.0
      with:
        name: nugetPackage
        path: Release\*.txt
        retention-days: 1

  publish:
    needs: build
    runs-on: windows-latest
    if: ${{github.ref == 'refs/heads/master'}}
    steps:
    - name: download nuget
      uses: actions/download-artifact@v3.0.0
      with:
        name: nugetPackage
        path: downloads
        
    - name: show download
      run: dir downloads
  
